[tool.poetry]
name = "textlen"
version = "0.1.5"
description = "A fast, simple CLI tool to calculate the character length, byte count, or word count of a string."
authors = ["Rud Faden <rudfaden@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
typer = "^0.13.1"

[tool.poetry.scripts]
textlen = "textlen.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
